{% set name = "tskit" %}
{% set version = "0.2.1" %}
{% set sha256 = "66ef6f1992342e69b184d2b14f5ae451852cf5f04ed02441d717c07cda1526da" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - tskit=tskit.cli:tskit_main
  skip: True  # [py<35]

# Following the guidance here for building against numpy:
# https://conda-forge.org/docs/meta.html#building-against-numpy
requirements:
  build:
    - {{ compiler('c') }}
  host:
    - setuptools
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - six
    - h5py
    - svgwrite
    - jsonschema

test:
  imports:
    - tskit

  commands:
    - tskit --help

about:
  home: http://github.com/tskit/tskit
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The tree sequence toolkit.
  description: Toolkit for storing and processing large-scale genetic genealogies.
  doc_url: 'http://tskit.readthedocs.io/en/stable'
  dev_url: 'https://github.com/tskit-dev/tskit'

extra:
  recipe-maintainers:
    - jeromekelleher
