travis:
  secure:
    BINSTAR_TOKEN: mVaueOacQmW96ukUkUfR5IjDV1Ui61pCCv4g5Di81j35Xwl50n9vlQ/60Yoq9WrcdYatdts0hzlDj/1USt3CeeVhTfZ5FhP1YzooZYFaCsjwldAhRVhvWaXRpNW2oglM7x/pgSWy3HqmcU2z13HKSs7XpYfc+7Ea0uEmhhHbY0/N65dgtY8Q5jTzP74ORk5zfyb6amgYMdLs4oYthgNcHenLYVBwjzg2XCnbJE2cfYDngRgjUM+StoEKsgMcMhCFQEXH1jTsRLhOnBGfQsf3fqGPfOtt5TmqakdXXs/cwy+7KzAou8GYH+rce3AFhgdmxkDwBCmDkdYKrLKqCT/9gga/ycweYSw6MDx36fo7mcmhaPAu9OX3EczRlpMi0gJnpjzU1PAdP5Njh0j/+GMelHBQeZ9SntAeF9Sa7UirxY+IEKvcBzPXR5Lel8JJIASAhu3674UFMNkTaJ5v6emVfb30A/Js2u4C7OphxSIPLW78Z0WB2DWmvo7fRW56km2T2qPNOS9aRWJlGqTwr+L3wXhvD4vxTs1eNNLD8WWxJhhZi++fgTRdkuHEJvmk1YzFZEsENCkqk3SfXxVvx4H45ZzPcIVv91VJ+zCFOY82iwFUUoJu0irlvfrLwYRBKEKxOVi+Khv8oBHpU2Bb3hmj9LdZcShxGgm/MLTWzOFTVQg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: false
